GOV-556 : API Compliance
openMF/ph-ee-identity-account-mapper pull request #11
Opened 2023-08-07 10:56 UTC by ankita10r

## Description

Implements [GOV-556](https://mifosforge.jira.com/browse/GOV-556)
## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above.

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-08-14 08:00 UTC, somanath21 requested changes

2023-08-14 08:00 UTC, somanath21 commented on src/main/java/org/mifos/identityaccountmapper/api/definition/AccountLookupApi.java
> +<<<<<<< Updated upstream
please rebase and remove these conflict indicators

2023-08-21 15:17 UTC, fynmanoj requested changes

2023-08-21 15:17 UTC, fynmanoj commented on src/main/java/org/mifos/identityaccountmapper/api/definition/UpdatePaymentModalityApi.java
> +<<<<<<< Updated upstream
remove conflict indicators

2023-09-03 17:42 UTC, closed without merging