GOV-517 Adding callback endpoint
openMF/ph-ee-identity-account-mapper pull request #21
Opened 2023-09-08 10:19 UTC by apurbraj

## Description

* Describe the changes made and why they were made.
* Add a link to teh design document or include the design bullet points related to this PR here.

_(Ignore if these details are present on the associated JIRA ticket)_

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Design related bullet points or design document link related to this PR added in the description above.

- [ ] Updated corresponding Postman Collection or Api documentation for the changes in this PR.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Add required Swagger annotation and update API documentation with details of any API changes if applicable

- [ ] Followed the naming conventions as given in https://docs.google.com/document/d/1Q4vaMSzrTxxh9TS0RILuNkSkYCxotuYk1Xe0CMIkkCU/edit?usp=sharing

2023-09-26 14:05 UTC, fynmanoj requested changes

2023-10-27 08:27 UTC, apurbraj commented on src/main/java/org/mifos/identityaccountmapper/api/definition/AccountLookupCallback.java
> +    @PutMapping("/accountLookup/callback")
Changed to /accountLookupCallback

2023-10-28 06:37 UTC, fynmanoj approved these changes

2023-10-28 06:37 UTC, fynmanoj commented on src/main/resources/application.yml
> +    url: jdbc:mysql:thin://localhost:3306/identity_account_mapper
is this overridden from the helm chart?

2023-11-01 07:12 UTC, merged